name: simple
on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: script
    run: action-a/entrypoint.sh
    shell: bash
      with:
        MY_NAME: "Steve"
